source "https://rubygems.org"

gem "capybara", "~> 2.4.4"
gem "cucumber", "~> 2.0.0"
gem "phantomjs", "~> 1.9.8.0", require: "phantomjs/poltergeist"
gem "poltergeist", "~> 1.6.0"
gem "rspec-expectations", "~> 3.3.0"
